resolver: lts-14.27
packages:
- .
extra-deps:
- ../tuple-ops
- git: https://github.com/0xCM/type-combinators.git
  commit: 58167dd4017b666ff592bb9493b0570a054aabdb
- git: https://github.com/pierric/haskell-src-exts.git
  commit: f75a5dbe2ec9fbc67df0936333e0665b033f9e22
extra-include-dirs:
- /home/jiasen/workspace/mxnet/build-1.6.0/include
extra-lib-dirs:
- /home/jiasen/workspace/mxnet/build-1.6.0
flags:
  fei-base:
    MXNet_geq_10600: true
